TOSMAKE_PATH=../../support/make/

COMPONENT=RadioCountToLedsAppC
BUILD_EXTRA_DEPS = log/SerialLogplayMsg.class
CLEAN_EXTRA = log/SerialLogplayMsg.class log/SerialLogplayMsg.java

#CFLAGS += -DPRINTF_BUFFER_SIZE=1000
#CFLAGS += -I$(TOSDIR)/lib/printf

include $(MAKERULES)
